server:
  port: 8081

spring:
  application: temp
#  mvc:
#    view:
#      suffix: .html
#      prefix: /templates/
#
#
#beetl:
#  enabled: true
#  suffix: .html
#  templatesPath: /templates/

#TAG.MyTestTag: com.dx.beetl.tag.MyTestTag




#logging:
#  level:
#    root: info





