server:
  port: 8084

spring:
  application: temp

  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml



#logging:classpath:resource.properties
#  level:=classpath:/ehcache.xml
#    root: info



