server:
  port: 8084

spring:
  application: temp

  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml



#logging:classpath:resource.properties
#  level:=classpath:/ehcache.xml
#    root: info


swagger:
  title: SpringBoot学习
  description: SpringBoot快速入门
  version: 1.0.0
  name: 测试项目
  url: http://www.baidu.com
  email: 670139644@qq.com


