server:
  #port: 8085
  ssl:
    key-store: classpath:key/server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: JKS

spring:
  application: https
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html




#logging:
#  level:
#    root: info



