server:
  port: 8085


web:
  upload-path: E:/temp/



#spring:
#  application: temp
#  mvc:
#    static-path-pattern: /image/**
#
#  resources:
#    static-locations: file:${web:upload-path}

logging:
  level:
    root: info



