---
spring:
  #数据库连接配置
  datasource:
    min-idle: 10
    test-on-borrow: true
    password: 123456
    test-while-idle: true
    max-active: 100
    validation-query: select 1
    min-evictable-idle-time-millis: 1800000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    test-on-return: true
    username: root
  #集群session存储方式
  session:
    store-type: none
  jpa:
    #是否在控制台打印sql语句
    show-sql: true
    #是否自动生成/修改数据库表
    generate-ddl: true
    hibernate:
      naming:
        #数据库表和字段命名策略
        implicit-strategy: com.tihom.security.rbac.repository.support.tihomImplicitNamingStrategy
    properties:
      hibernate:
        #打印sql语句时是否格式化
        format_sql: true


server:
  port: 8080
  #session超时时间，单位秒
  session:
    timeout: 600

 ######################   自定义安全模块控制 ######################
dx:
  security:

    ##图片验证码配置项，参见ImageCodeProperties
    code:
      image:
        width: 100
        length: 4
        expireIn: 30
        url: /user/*
        height: 30
      ##短信验证码配置项，参见SmsCodeProperties
      sms:
        length: 6
        expireIn: 60
        url: /user/*
    ##社交登录功能拦截的url,参见SocilaProperties
    social:
      #QQ登录配置，参见QQProperties
      qq:
        app-id:
        providerId: callback.do
        app-secret:
      filterProcessesUrl: /qqLogin
      #微信登录配置，参见WeixinProperties
      weixin:
        app-id: wxd99431bbff8305a0
        providerId: weixin
        app-secret: 60f78681d063590a469f1b297feff3c4

    ##浏览器环境配置项，参见BrowserProperties
    browser:
      rememberMeSeconds: 294000
      signInResponseType: REDIRECT
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
      ##session管理相关配置，参见SessionProperties
      session:
        maximumSessions: 1
        sessionInvalidUrl: /tihom-session-invalid.html
        maxSessionsPreventsLogin: false
      signInPage: /demo-signIn.html
      singInSuccessUrl: /manage.html
    ##认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
    oauth2:
      clients[0]:
        clientId: dx
        accessTokenValidateSeconds: 3600
        clientSecret: tihomsecret
      #使用jwt时为token签名的秘钥
      jwtSigningKey: tihom
      #OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
      tokenStore: redis
      clients[1]:
        clientId: test
        clientSecret: test
