server:
  port: 8082

spring:
  application: temp
  jpa:
    show-sql: true
    properties:
      hibernate:
        #mysql：org.hibernate.dialect.MySQL5InnoDBDialect  H2：org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create


database:
  #-------------------------mysql-------------------------------------
#  type: mysql
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/dx?characterEncoding=UTF-8
#  username: root
#  password: root
#

  #-------------------------H2-------------------------------------
  type: H2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test
  username: root
  password: root





#logging:
#  level:
#    root: info



