server:
  port: 8083

spring:
  application: mq-simple
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    #connection-timeout: 15000





#
#logging:
#  level:
#    root: info


