server:
  port: 8088

spring:
  application: auth-simple


imooc:
  security:
    browser:
      code:
        image:
          width: 100
          height: 30
          length: 6
      loginPage: /demo-login.html
      loginType: REDIRECT




logging:
  level:
    root: info



