server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dx?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root






#logging:
#  level:
#    root: info



